import nii_preprocessing as nii_prep
import atlas as atlas_prep
import edf_preprocessing as edf_prep
import csv_preprocessing as csv_prep
import shift_handling as shift_handling
import labeling as label

import nibabel as nib
import numpy as np
import time
import pandas as pd
import subprocess
import os
import sys
import argparse
from pathlib import Path


# ============================================================
# Default paths  (fallbacks when not supplied via CLI)
# ============================================================

_DEFAULT_BASE    = Path(r"C:\Users\maely\OneDrive - UCL\MASTER GBIO\TFE\Data")
_DEFAULT_PROJECT = Path(r"C:\Users\maely\OneDrive - UCL\MASTER GBIO\TFE")

DEFAULT_MNI_PATH            = _DEFAULT_BASE / "Atlas_Maps" / "MNI152_T1_1mm_brain.nii.gz"
DEFAULT_AAL_PATH            = _DEFAULT_BASE / "Atlas"      / "aal.nii.gz"
DEFAULT_AAL_TXT_PATH        = _DEFAULT_BASE / "Atlas"      / "AAL_atlas.txt"
DEFAULT_BRAIN_MASK_MNI_PATH = _DEFAULT_BASE / "Atlas_Maps" / "MNI152_T1_2mm_brain_mask.nii.gz"
DEFAULT_ELECTROLOC_PARENT   = _DEFAULT_PROJECT / "MasterThesis_ElectroLoc"


# ============================================================
# CLI
# ============================================================

def parse_args():
    parser = argparse.ArgumentParser(
        prog="main.py",
        description=(
            "iEEG electrode localization and labeling pipeline.\n\n"
            "Minimal usage (default atlas & ElectroLoc paths):\n"
            "  python main.py CT.nii.gz MRI.nii.gz brain_mask_CT.nii.gz iEEG.edf\n\n"
            "With custom output dir and ElectroLoc:\n"
            "  python main.py CT.nii.gz MRI.nii.gz brain_mask_CT.nii.gz iEEG.edf\n"
            "      -o ./results  --electroloc path/to/MasterThesis_ElectroLoc\n\n"
            "With custom atlas:\n"
            "  python main.py CT.nii.gz MRI.nii.gz brain_mask_CT.nii.gz iEEG.edf\n"
            "      --mni MNI.nii.gz --atlas aal.nii.gz --atlas-txt AAL_atlas.txt\n"
            "      --brain-mask-mni brain_mask_mni.nii.gz\n\n"
            "Note: electrode_info CSV files are entered interactively at runtime\n"
            "(they are generated by ElecTool during the preprocessing step)."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    # ── Required positional inputs ────────────────────────────────────────────
    parser.add_argument(
        "ct",
        metavar="CT_PATH",
        type=Path,
        help="Skull-stripped CT volume (.nii / .nii.gz).",
    )
    parser.add_argument(
        "mri",
        metavar="MRI_PATH",
        type=Path,
        help="Skull-stripped T1 MRI volume (.nii / .nii.gz).",
    )
    parser.add_argument(
        "brain_mask_ct",
        metavar="BRAIN_MASK_CT",
        type=Path,
        help="CT brain mask (.nii / .nii.gz).",
    )
    parser.add_argument(
        "edf",
        metavar="IEEG_PATH",
        type=Path,
        help="iEEG recording (.edf).",
    )

    # ── Output directory ──────────────────────────────────────────────────────
    parser.add_argument(
        "-o", "--output",
        metavar="OUTPUT_DIR",
        type=Path,
        default=None,
        help=(
            "Root output directory. "
            "Default: out/ subfolder next to the CT file."
        ),
    )

    # ── ElectroLoc ────────────────────────────────────────────────────────────
    parser.add_argument(
        "--electroloc",
        metavar="ELECTROLOC_PARENT",
        type=Path,
        default=DEFAULT_ELECTROLOC_PARENT,
        help=(
            "Parent directory containing the ElectroLoc package. "
            f"Default: {DEFAULT_ELECTROLOC_PARENT}"
        ),
    )

    # ── Optional atlas overrides (all 4 required together, or none) ───────────
    atlas_grp = parser.add_argument_group(
        "Atlas overrides",
        "All four flags must be supplied together; omit all to use the built-in defaults.",
    )
    atlas_grp.add_argument(
        "--mni",
        metavar="PATH",
        type=Path,
        default=None,
        help="MNI152 T1 1 mm brain template (.nii / .nii.gz).",
    )
    atlas_grp.add_argument(
        "--atlas",
        metavar="PATH",
        type=Path,
        default=None,
        help="AAL (or custom) atlas volume (.nii / .nii.gz).",
    )
    atlas_grp.add_argument(
        "--atlas-txt",
        metavar="PATH",
        type=Path,
        default=None,
        help="Text file mapping atlas label indices to region names.",
    )
    atlas_grp.add_argument(
        "--brain-mask-mni",
        metavar="PATH",
        type=Path,
        default=None,
        help="MNI brain mask used for atlas dilation (.nii / .nii.gz).",
    )

    return parser.parse_args()


# ============================================================
# Validation & helpers
# ============================================================

def _require_file(path: Path, label: str) -> None:
    if not path.exists():
        raise FileNotFoundError(f"[{label}] File not found: {path}")


def validate_inputs(args) -> None:
    _require_file(args.ct,            "CT")
    _require_file(args.mri,           "MRI")
    _require_file(args.edf,           "iEEG EDF")
    _require_file(args.brain_mask_ct, "CT brain mask")
    _require_file(args.electroloc,    "ElectroLoc parent dir")

    atlas_args = (args.mni, args.atlas, args.atlas_txt, args.brain_mask_mni)
    n_provided = sum(a is not None for a in atlas_args)
    if 0 < n_provided < 4:
        raise ValueError(
            "Atlas overrides: supply all four flags together "
            "(--mni, --atlas, --atlas-txt, --brain-mask-mni) or none of them."
        )


def resolve_atlas_paths(args):
    """Return (mni, aal, aal_txt, brain_mask_mni) — custom or built-in defaults."""
    if args.atlas is not None:
        return args.mni, args.atlas, args.atlas_txt, args.brain_mask_mni
    return (
        DEFAULT_MNI_PATH,
        DEFAULT_AAL_PATH,
        DEFAULT_AAL_TXT_PATH,
        DEFAULT_BRAIN_MASK_MNI_PATH,
    )


def build_output_dirs(base_output: Path) -> dict:
    file_keys = {
        "output_csv_ElectroLoc",
        "contacts_shifted_corrected",
        "contact_shifted_corrected_mask",
    }
    dirs = {
        "output_dir":                     base_output,
        "output_dir_coregistration":      base_output / "coregistration",
        "output_dir_input_ElectroLoc":    base_output / "input_ElectroLoc",
        "output_dir_mask":                base_output / "mask_generated",
        "output_csv_ElectroLoc":          base_output / "output_ElectroLoc.csv",
        "contacts_shifted_corrected":     base_output / "contacts_shifted_corrected.csv",
        "contact_shifted_corrected_mask": base_output / "contact_shifted_corrected.nii.gz",
    }
    for key, path in dirs.items():
        if key not in file_keys:
            path.mkdir(parents=True, exist_ok=True)
    return dirs


# ============================================================
# Main pipeline
# ============================================================

if __name__ == "__main__":

    args = parse_args()
    validate_inputs(args)

    # ── Resolve input paths ───────────────────────────────────────────────────
    path_CT            = args.ct.resolve()
    path_mri           = args.mri.resolve()
    path_edf           = args.edf.resolve()
    brain_mask_CT_path = args.brain_mask_ct.resolve()
    electroloc_parent  = args.electroloc.resolve()

    base_output = args.output.resolve() if args.output else (path_CT.parent / "out")
    dirs = build_output_dirs(base_output)

    output_dir                  = dirs["output_dir"]
    output_dir_coregistration   = dirs["output_dir_coregistration"]
    output_dir_input_ElectroLoc = dirs["output_dir_input_ElectroLoc"]
    output_dir_mask             = dirs["output_dir_mask"]
    output_csv_ElectroLoc       = dirs["output_csv_ElectroLoc"]

    MNI_path, AAL_path, AAL_txt_path, brain_mask_MNI_path = resolve_atlas_paths(args)

    print("=" * 60)
    print("Pipeline inputs")
    print("=" * 60)
    print(f"  CT              : {path_CT}")
    print(f"  MRI             : {path_mri}")
    print(f"  iEEG EDF        : {path_edf}")
    print(f"  CT brain mask   : {brain_mask_CT_path}")
    print(f"  Atlas (AAL)     : {AAL_path}")
    print(f"  MNI template    : {MNI_path}")
    print(f"  ElectroLoc      : {electroloc_parent}")
    print(f"  Output dir      : {output_dir}")
    print("=" * 60)
    print()

    # ============================================================
    # Data Preprocessing
    # ============================================================

    print("Starting data preprocessing...")
    start_data_prep = time.time()

    data_edf, channel_names = edf_prep.load_edf(
        str(path_edf),
        str(output_dir)
    )

    output_electrode_info = edf_prep.extract_electrodes(
        channel_names,
        str(path_edf),
        str(output_dir_input_ElectroLoc)
    )

    mask_dir_electrodes = nii_prep.electrode_mask(
        str(path_CT),
        str(output_dir_mask)
    )

    mask_dir_surface = nii_prep.extract_surface_mask(
        str(brain_mask_CT_path),
        str(output_dir_mask)
    )

    entry_point_voxel_path, entry_point_world_path = csv_prep.entry_point_coordinates(
        mask_dir_surface,
        mask_dir_electrodes,
        str(output_dir_input_ElectroLoc)
    )

    end_data_prep = time.time()
    print(f"Data preprocessing completed in {end_data_prep - start_data_prep:.1f} s.")

    # ============================================================
    # Manual Electrode Identification  (interactive — files generated above)
    # ============================================================

    print("\nStarting manual electrode identification...")
 

    electrode_info_path, df_electrode_info = csv_prep.get_valid_csv_path(
        prompt="Enter path to electrode_info.csv: ",
        required_columns=["nb_contacts", "vox_x", "vox_y", "vox_z"],
        name="electrode_info.csv"
    )

    electrode_info_world_path, df_electrode_info_world = csv_prep.get_valid_csv_path(
        prompt="Enter path to electrode_info_world.csv: ",
        required_columns=["electrode_id", "nb_contacts", "world_x", "world_y", "world_z"],
        name="electrode_info_world.csv"
    )

    print("Manual electrode identification completed.")

    # ============================================================
    # Electrode Localization with ElectroLoc
    # ============================================================

    env = os.environ.copy()
    env["PYTHONPATH"] = str(electroloc_parent) + os.pathsep + env.get("PYTHONPATH", "")

    cmd = [
        sys.executable,
        "-m", "ElectroLoc",
        str(path_CT),
        str(brain_mask_CT_path),
        str(electrode_info_path),
        "-o",
        str(output_csv_ElectroLoc),
    ]

    print("\nRunning ElectroLoc...")
    subprocess.run(cmd, check=True, env=env)
    print(f"Electrode localization completed. Output: {output_csv_ElectroLoc}")

    nii_prep.create_contact_mask_from_csv(
        str(output_csv_ElectroLoc),
        str(path_CT),
        str(output_dir)
    )

    # ============================================================
    # Contact Labeling
    # ============================================================

    print("\nStarting contact labeling...")
    start_contact_labeling = time.time()

    reordered_contact, contact_final = label.numbering_contact(
        str(output_csv_ElectroLoc),
        str(electrode_info_world_path),
        str(output_dir)
    )

    shifted_electrode_ids = shift_handling.selection_of_potential_shifted_electrode(
        reordered_contact,
        mask_dir_electrodes,
        str(electrode_info_world_path)
    )

    contact_shifted_corrected_path, df_out = shift_handling.shift_selected_electrodes_with_mask(
        reordered_contact,
        str(electrode_info_world_path),
        mask_dir_electrodes,
        shifted_electrode_ids,
        output_path=str(dirs["contacts_shifted_corrected"]),
        max_shift_mm=20,
        step_mm=0.1,
        lambda_EP=0.5,
        c0_mask_threshold_mm=0.5
    )

    nii_prep.create_contact_mask_from_csv(
        contact_shifted_corrected_path,
        ct_path=str(path_CT),
        output_dir=str(output_dir)
    )

    # ============================================================
    # Atlas Co-registration
    # ============================================================

    print("\nStarting atlas co-registration...")

    coregistered_MNI_to_mri, mapping_MNI_to_MRI = atlas_prep.coregister_1_to_2(
        str(MNI_path),
        str(path_mri),
        str(output_dir_coregistration)
    )

    coregistered_aal_to_MNI_coregistered, mapping_aal_to_MNI = atlas_prep.coregister_1_to_2(
        str(AAL_path),
        coregistered_MNI_to_mri,
        str(output_dir_coregistration)
    )

    coregistered_brain_mask_MNI_to_MRI, mapping_brain_mask_MNI_to_MRI = atlas_prep.coregister_1_to_2(
        str(brain_mask_MNI_path),
        str(path_mri),
        str(output_dir_coregistration)
    )

    coregistered_CT_to_MRI, mapping_CT_to_MRI = nii_prep.coregistration_CT_to_MRI(
        str(path_CT),
        str(path_mri),
        str(output_dir_coregistration)
    )

    mri_img = nib.load(str(path_mri))

    dilate_atlas_path = atlas_prep.dilate_atlas_labels(
        str(coregistered_aal_to_MNI_coregistered),
        str(coregistered_brain_mask_MNI_to_MRI),
        6,
        str(output_dir_coregistration)
    )

    label_output = label.label_contacts(
        contact_shifted_corrected_path,
        str(dilate_atlas_path),
        str(AAL_txt_path),
        str(mapping_CT_to_MRI),
        mri_img.affine,
        str(output_dir)
    )

    end_contact_labeling = time.time()
    print(f"Contact labeling completed in {end_contact_labeling - start_contact_labeling:.1f} s.")
